Dotnet Project/Tutorial/TutorialWebApp/Controllers/AdminTagsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TutorialWebApp.Data;
using TutorialWebApp.Models.Domain;
using TutorialWebApp.Models.ViewModels;
using TutorialWebApp.Repositories;


namespace TutorialWebApp.Controllers
{

    [Authorize(Roles = "Admin")]
    public class AdminTagsController : Controller
    {
        private readonly ItagRepository tagRepository;

        public AdminTagsController(ItagRepository tagRepository)
        {
            this.tagRepository = tagRepository;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Add")]
        public async Task<IActionResult> Add(AddTagRequest addTagRequest)
        {
            ValidateAddTagRequest(addTagRequest);

            if (ModelState.IsValid == false)
            {
                return View();
            }

            var tag = new Tag
            {
                Name = addTagRequest.Name,
                DisplayName = addTagRequest.DisplayName
            };

            await tagRepository.AddAsync(tag);

            return RedirectToAction("List"); 
        }

        [HttpGet]
        [ActionName("List")]
        public async Task<IActionResult> List()
        {
            var tags = await tagRepository.GetAllAsync();
            return View(tags);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var tag = await tagRepository.GetAsync(id);
            if (tag != null)
            {
                var editTagRequest = new EditTagRequest
                {
                    Id = tag.Id,
                    Name = tag.Name,
                    DisplayName = tag.DisplayName
                };
                return View(editTagRequest);
            }
                return View(null);
        }

        [HttpPost]
        public async Task<IActionResult>  Edit(EditTagRequest editTagRequest)
        {
            var tag = new Tag
            {
                Id = editTagRequest.Id,
                Name = editTagRequest.Name,
                DisplayName = editTagRequest.DisplayName
            };

            var updatedTag = await tagRepository.UpdateAsync(tag);

            if (updatedTag != null)
            {
              
            }
            else {
               }
                
                return RedirectToAction("Edit", new { id = editTagRequest.Id });
        }
            

        [HttpPost]
        public async Task<IActionResult> Delete(EditTagRequest editTagRequest)
        {
        var deletedTag = await tagRepository.DeleteAsync(editTagRequest.Id);

            if(deletedTag != null)
            {
                return RedirectToAction("List");
            }
            return RedirectToAction("Edit", new { id = editTagRequest.Id });
        }

        private void ValidateAddTagRequest(AddTagRequest request)
        {
            if (request.Name is not null && request.DisplayName is not null)
            {
                if (request.Name == request.DisplayName)
                {
                    ModelState.AddModelError("DisplayName", "Name cannot be the same as DisplayName");
                }
            }
        }
    }
}

Dotnet Project/Tutorial/TutorialWebApp/Controllers/AdminTutorialPostsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TutorialWebApp.Models.Domain;
using TutorialWebApp.Models.ViewModels;
using TutorialWebApp.Repositories;

namespace TutorialWebApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminTutorialPostsController : Controller
    {
        private readonly ItagRepository tagRepository;
        private readonly ITutorialPostRepository tutorialPostRepository;
        public AdminTutorialPostsController(ItagRepository tagRepository, ITutorialPostRepository tutorialPostRepository)
        {
            this.tagRepository = tagRepository;
            this.tutorialPostRepository = tutorialPostRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var tags = await tagRepository.GetAllAsync();
            var model = new AddTutorialPostRequest
            {
                Tags = tags.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() })
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddTutorialPostRequest addTutorialPostRequest)
        {
            // Map view model to domain model
            var tutorialPost = new TutorialPost
            {
                Heading = addTutorialPostRequest.Heading,
                PageTitle = addTutorialPostRequest.PageTitle,
                Content = addTutorialPostRequest.Content,
                ShortDescription = addTutorialPostRequest.ShortDescription,
                FeaturedImageUrl = addTutorialPostRequest.FeaturedImageUrl,
                UrlHandle = addTutorialPostRequest.UrlHandle,
                PublishedDate = addTutorialPostRequest.PublishedDate,
                Author = addTutorialPostRequest.Author,
                Visible = addTutorialPostRequest.Visible,
            };

            var selectedTags = new List<Tag>();
            foreach (var selectedTagId in addTutorialPostRequest.SelectedTags)
            {
                var selectedTagIdAsGuid = Guid.Parse(selectedTagId);
                var existingTag = await tagRepository.GetAsync(selectedTagIdAsGuid);

                if (existingTag != null)
                {
                    selectedTags.Add(existingTag);
                }
            }

            // Mapping tags back to domain model
            tutorialPost.Tags = selectedTags;


            await tutorialPostRepository.AddAsync(tutorialPost);

            return RedirectToAction("Add");
        }


        [HttpGet]
        public async Task<IActionResult> List()
        {
            // Call the repository 
            var tutorialPosts = await tutorialPostRepository.GetAllAsync();

            return View(tutorialPosts);
        }



        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            // Retrieve the result from the repository 
            var tutorialPost = await tutorialPostRepository.GetAsync(id);
            var tagsDomainModel = await tagRepository.GetAllAsync();

            if (tutorialPost != null)
            {
                // map the domain model into the view model
                var model = new EditTutorialPostRequest
                {
                    Id = tutorialPost.Id,
                    Heading = tutorialPost.Heading,
                    PageTitle = tutorialPost.PageTitle,
                    Content = tutorialPost.Content,
                    Author = tutorialPost.Author,
                    FeaturedImageUrl = tutorialPost.FeaturedImageUrl,
                    UrlHandle = tutorialPost.UrlHandle,
                    ShortDescription = tutorialPost.ShortDescription,
                    PublishedDate = tutorialPost.PublishedDate,
                    Visible = tutorialPost.Visible,
                    Tags = tagsDomainModel.Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    }),
                    SelectedTags = tutorialPost.Tags.Select(x => x.Id.ToString()).ToArray()
                };

                return View(model);

            }

            // pass data to view
            return View(null);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditTutorialPostRequest editTutorialPostRequest)
        {
            // map view model back to domain model
            var tutorialPostDomainModel = new TutorialPost
            {
                Id = editTutorialPostRequest.Id,
                Heading = editTutorialPostRequest.Heading,
                PageTitle = editTutorialPostRequest.PageTitle,
                Content = editTutorialPostRequest.Content,
                Author = editTutorialPostRequest.Author,
                ShortDescription = editTutorialPostRequest.ShortDescription,
                FeaturedImageUrl = editTutorialPostRequest.FeaturedImageUrl,
                PublishedDate = editTutorialPostRequest.PublishedDate,
                UrlHandle = editTutorialPostRequest.UrlHandle,
                Visible = editTutorialPostRequest.Visible
            };

            // Map tags into domain model

            var selectedTags = new List<Tag>();
            foreach (var selectedTag in editTutorialPostRequest.SelectedTags)
            {
                if (Guid.TryParse(selectedTag, out var tag))
                {
                    var foundTag = await tagRepository.GetAsync(tag);

                    if (foundTag != null)
                    {
                        selectedTags.Add(foundTag);
                    }
                }
            }

            tutorialPostDomainModel.Tags = selectedTags;

            // Submit information to repository to update
            var updatedBlog = await tutorialPostRepository.UpdateAsync(tutorialPostDomainModel);

            if (updatedBlog != null)
            {
                // Show success notification
                //TempData["SuccessMessage"] = "Tutorial post updated successfully!";
                return RedirectToAction("Edit");
            }

            // Show error notification
            //TempData["ErrorMessage"] = "Error updating the tutorial post. Please try again.";
            return RedirectToAction("Edit");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditTutorialPostRequest editTutorialPostRequest)
        {
            var deletedBlogPost = await tutorialPostRepository.DeleteAsync(editTutorialPostRequest.Id);

            if (deletedBlogPost != null)
            {
                // Show success notification
               // TempData["SuccessMessage"] = "Tutorial post deleted successfully!";
                return RedirectToAction("List");
            }

           // TempData["ErrorMessage"] = "Error deleting the tutorial post. Please try again.";
            return RedirectToAction("Edit", new { id = editTutorialPostRequest.Id });

        }
    }
}

Dotnet Project/Tutorial/TutorialWebApp/Views/Shared/_AboutUs.cshtml
  <div>

    <h1 className="mt-5">About Coding Nexus</h1>
          <p>
               Welcome to Coding Nexus, your go-to platform for exploring and
               sharing knowledge about various technologies. Our mission is to
               create a thriving community of tech enthusiasts, where learning
               and collaboration are at the forefront.
          </p>
    <h2 className="mt-5">What is Coding Nexus?</h2>
          <p>
                Coding Nexus is a dynamic online hub where individuals passionate
                about technology come together to share their expertise. Whether
                you're a seasoned developer, a tech enthusiast, or someone just
                starting their coding journey, Coding Nexus provides a space for
                you to contribute tutorials and gain insights from a diverse
                community.
          </p>  
    <h2 className="mt-5">Our Vision</h2>
    <p>
        At Coding Nexus, we envision a world where knowledge is
        accessible and shared freely. Our platform aims to bridge the gap
        between experts and learners, fostering a collaborative
        environment where everyone has the opportunity to contribute and
        grow.
    </p>
    <h2 className="mt-5">What Sets Us Apart?</h2>
    <ul>
        <li>
            <strong>Diverse Content:</strong> Explore a wide range of
            tutorials covering various technologies, programming languages,
            frameworks, and tools. Our diverse content ensures that there's
            something valuable for everyone, from beginners to experienced
            developers.
        </li>
        <li>
            <strong>Community Engagement:</strong> Coding Nexus is more
            than just a tutorial platform; it's a community-driven space.
            Engage in discussions, seek help, and connect with like-minded
            individuals who share your passion for coding and technology.
        </li>
        <li>
            <strong>User-Friendly Interface:</strong> We believe in making
            learning accessible and enjoyable. Our user-friendly interface
            makes it easy to navigate through tutorials, contribute your
            own, and interact with the Coding Nexus community.
        </li>
    </ul>
    <h2 className="mt-5">How You Can Contribute</h2>
    <ul>
        <li>
            <strong>Share Your Knowledge:</strong> Whether you've mastered
            a new programming language, discovered a helpful coding trick,
            or want to showcase a project, Coding Nexus is the place to
            share your knowledge with the world.
        </li>
        <li>
            <strong>Learn and Grow:</strong> Explore tutorials posted by
            others, ask questions, and enhance your skills. Coding Nexus is
            not just a platform for sharing; it's a place to continuously
            learn and grow as a technologist.
        </li>
        <li>
            <strong>Connect with Peers:</strong> Connect with fellow
            learners, mentors, and collaborators. Coding Nexus provides a
            space for networking and building meaningful connections within
            the tech community.
        </li>
    </ul>
    <p className="mt-5">
        <strong>Join Us on the Coding Journey!</strong> Coding Nexus is
        more than a platform; it's a journey of discovery and
        collaboration. Whether you're here to contribute, learn, or
        connect, we invite you to be a part of our growing community.
        Together, let's build a nexus of knowledge that empowers and
        inspires the tech community worldwide.
    </p>
    <p>
        <em>
            Start exploring, start coding, and welcome to Coding Nexus!
        </em>
    </p>

</div>

Dotnet Project/Tutorial/TutorialWebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TutorialWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TutorialWebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

    <link href='https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js'></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Coding Nexus</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="https://coding-nexus.mykajabi.com/opt-in" target="_blank">Subscribe</a>
                        </li>

                      @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                      {
                          
                         <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Admin
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item"
                                       asp-area=""
                                       asp-controller="AdminTags"
                                       asp-action="Add">
                                        Add Category
                                    </a>
                                </li>

                                <li>
                                    <a class="dropdown-item"
                                       asp-area=""
                                       asp-controller="AdminTags"
                                       asp-action="List">
                                        Show all Categories
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item"
                                       asp-area=""
                                       asp-controller="AdminTutorialPosts"
                                       asp-action="Add">
                                        Add a new Tutorial 
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item"
                                       asp-area=""
                                       asp-controller="AdminTutorialPosts"
                                       asp-action="List">
                                        Show All Tutorials 
                                    </a>
                                </li>
                                    <li>
                                        <a class="dropdown-item"
                                           asp-area=""
                                           asp-controller="AdminUsers"
                                           asp-action="List">
                                            All Users
                                        </a>
                                    </li>
                               </ul>
                            </li>
                      }

                    </ul>
                            <div class="d-flex align-items-center">

                                @if (signInManager.IsSignedIn(User))
                                {
                                    <div class="me-3 text-light">
                                        @User?.Identity?.Name
                                    </div>

                                    <a class="btn me-3 bg-light text-dark"
                                       asp-area=""
                                       asp-controller="Account"
                                       asp-action="Logout">Logout</a>
                                }
                                else
                                {
                                    <a class="btn me-3 bg-light text-dark"
                                       asp-area=""
                                       asp-controller="Account"
                                       asp-action="Login">Login</a>

                                    <a class="btn me-3 bg-light text-dark"
                                       asp-area=""
                                       asp-controller="Account"
                                       asp-action="Register">Register</a>

                                }

                            </div>
                </div>
            </div>
        </nav>
    </header>
    <div >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Coding Nexus - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>